// Multi-language UI labels for VIP Dashboard
export const labelsMap: Record<string, Record<string, string>> = {
    pt: {
      badge: 'Painel Executivo Ativo',
      title: 'Dashboard VIP iRunBets',
      desc: 'Análise probabilística e registo integrado para controlo absoluto de banca.',
      tabBanca: '📊 Registo & Banca',
      tabIa: '✨ IA iRunBets',
      tabFavoritos: '⭐ Equipas & Ligas',
      sportFilterTitle: 'Filtro de Desporto Ativo (1 Clique)',
      sportFilterDesc: 'Recalcule instantaneamente ROI, Ganhos e Históricos de correspondência',
      allSports: '🌍 Todos os Desportos',
      football: '⚽ Futebol',
      tennis: '🎾 Ténis',
      basketball: '🏀 Basquetebol',
      others: '🎲 Outros',
      matrixBtn: '📊 MATRIX DE DETALHES LIGAS / MERCADOS',
      bancaInicial: 'Banca Inicial',
      casaPendente: 'CASA',
      semCasa: '⚠️ SEM CASA',
      editar: 'Editar',
      bancaDeControlo: 'Banca de controlo de risco',
      bancaGeralFinal: 'Banca Geral Final',
      globalApostas: 'Global de todas as apostas',
      lucroFiltro: 'Lucro no Filtro',
      positivo: '▲ POSITIVO',
      variancia: '▼ VARIÂNCIA',
      roiFiltro: 'ROI do Filtro',
      retornoDesporto: 'Retorno do desporto selecionado',
      taxaAcerto: 'Taxa de Acerto',
      resolvidas: 'resolvidas',
      gaugeTitle: 'Leitura Rápida de Reds / Greens / Devolution',
      gaugeDesc: 'Contagem e proporção corrente de apostas em:',
      gaugeNoBets: 'Nenhuma aposta registada neste desporto para renderizar o Neon Gauge.',
      ganhas: 'Ganhas',
      perdidas: 'Perdidas',
      devolvidas: 'Devolvidas',
      pendentes: 'Pendentes',
      simples: 'Simples',
      multiplas: 'Múltiplas',
      comparadorTitle: '🎯 Comparador Simples vs Múltiplas',
      comparadorDesc: 'Taxa de eficácia de Greens/Reds integrados (iPhone iOS & Web)',
      comparadorNoSlips: 'Nenhum boletim sincronizado (iPhone ou Web) para processar métricas.',
      boletinsSimples: 'Boletins Simples',
      boletinsMultiplos: 'Boletins Múltiplos',
      apostasIphone: 'Apostas do iPhone:',
      apostasWeb: 'Apostas da Web:',
      total: 'Total',
      eficacia: 'Eficácia (Greens):',
      registarEntradaBadge: 'Registar Entrada Real',
      multiplaPopup: 'Múltipla Pop-up ↗',
      nomeEvento: 'Nome do Evento / Equipas',
      desporto: 'Desporto',
      mercadoLinha: 'Mercado / Linha',
      competiçao: 'Liga / Competição',
      tipoMercado: 'Tipo de Mercado',
      oddOferecida: 'Odd Oferecida',
      montante: 'Montante (€)',
      estadoInicial: 'Estado Entrada Inicial',
      registarBtn: 'Registar Entrada de Valor 🚀',
      graficoBanca: 'Gráfico Evolutivo de Banca (Histórico Real)',
      bancaAtual: 'Banca Atual:',
      graficoNoBets: 'Registe as suas apostas ou selecione outro filtro de desporto para ver a evolução.',
      historicoTitle: 'Histórico de Apostas Desportivas ({0} no filtro)',
      historicoTip: 'Dica: Clique no estado para alternar os ganhos rapidamente',
      historicoNoBets: 'Nenhuma aposta registada para este desporto. Use o formulário à esquerda para adicionar ou registar!',
      tabelaJogo: 'Jogo / Desporto',
      tabelaMercado: 'Mercado',
      tabelaOdd: 'Odd',
      tabelaStake: 'Stake',
      tabelaLucro: 'Lucro/Prej.',
      tabelaData: 'Data',
      tabelaEstado: 'Estado',
      tabelaAçao: 'Ação',
      painelUnificadoTitle: 'Painel Unificado: Boletins de Apostas (iOS & Web)',
      painelUnificadoDesc: 'Espaço segmentado e seguro em tempo real. Os seus registos do iPhone (betSlips) e do site (webBetSlips) agregam-se aqui sem risco de sobreposição.',
      registarBoletimBtn: 'Registar Boletim Web 🖥️',
      cloudSys: 'Cloud Sync Protegido',
      iphoneLabel: '📱 iPhone',
      webLabel: '🖥️ Web',
      loginPrompt: 'Inicie sessão no painel iRunBets para ligar e visualizar os seus boletins em tempo real do iPhone.',
      loadingMatches: 'Pesquisando correspondências no servidor...',
      noSlipsCloud: 'Nenhum boletim de apostas ativo encontrado no Firebase para esta conta. Faça apostas na nossa aplicação nativa iOS e estas aparecerão listadas de imediato!',
      boletimSimples: 'Boletim Simples',
      boletimMultiplo: 'Boletim Múltiplo',
      apagarPerm: 'Apagar permanente?',
      sim: 'Sim 🚨',
      nao: 'Não',
      editarBtn: 'Editar 📝',
      apagarBtn: 'Apagar 🗑️',
      eventos: 'Eventos',
      recolher: 'Recolher ▲',
      expandir: 'Expandir ▼',
      pE_titulo: 'Matriz de Resultados - Probabilidade Matemática Ajustada',
      pE_noResult: 'Defina os fatores humanos à esquerda e clique no botão para computar as probabilidades de Poisson e fatores humanos combinados.',
      pE_mercado1x2: 'Probabilidades do Mercado 1X2 (%)',
      pE_btts: 'Ambas Marcam (BTTS)',
      pE_mais15: 'Mais de 1.5 Golos',
      pE_mais25: 'Mais de 2.5 Golos',
      pE_empate: 'Empate (X)',
      pE_vitoria: 'Vitória',
      pE_casa: 'Casa',
      pE_fora: 'Fora',
      pE_gerarBtn: 'Gerar Análise IA Híbrida 🤖📊',
      pE_gerandoText: 'IA A calcular Probabilidades Híbridas...',
      pE_relatorioTitle: 'Relatório Analítico de Elite iRunBets Specialist',
      pE_relatorioGerando: 'iR-Engine-v3.5 a cruzar matriz de Poisson com fatores de terreno humanos...',
      pE_relatorioSecs: 'Isto pode demorar alguns segundos, a processar a recolha de conhecimento estatístico...',
      pE_relatorioPrompt: 'Pronto para acionar redigenda especialista. Clique em "Gerar Análise IA Híbrida 🤖📊" para consultar o modelo avançado.',
      pE_casaLabel: 'Equipa da Casa (Golos esperados standard)',
      pE_foraLabel: 'Equipa de Fora (Golos esperados standard)',
      pE_relvado: 'Estado do Relvado',
      pE_lesões: 'Lesões Importantes (Última hora)',
      pE_condições: 'Condições Climáticas',
      pE_motivaçao: 'Motivação',
      t_badge: '⚡ CONSOLA ESTATÍSTICA PREMIUM (MONITOR COCKPIT 14")',
      t_sub: 'IrUnBets Advanced Analytical Core • Segmento de Mercado:',
      t_fechar: '✕ FECHAR TERMINAL',
      t_diagnostico: 'Diagnóstico Inteligente do Segmento',
      t_diagnosticoDesc: 'Os dados estatísticos apresentados resultam de todas as apostas efetuadas baseando-se no desporto selecionado. O simulador recalculou todas as métricas em tempo de execução para alimentar este dashboard.',
      t_resumo: 'Resumo do Estado',
      t_leaguesTitle: 'Competições & Ligas Ativas (Eficiência 🏆)',
      t_leaguesSub: 'Taxa de acerto real e retorno líquido acumulado por liga desportiva',
      t_marketsTitle: 'Comportamento de Mercados (Foco 🎯)',
      t_marketsSub: 'ROI de investimento proporcional a cada tipo de mercado',
      t_vol: 'Volume Total de Stake',
      t_med: 'Média por entrada:',
      t_closeBtn: 'Fechar Consola',
      s_estatuto: 'Estatuto de Subscrição do Utilizador (Sync iTunes & Web)',
      s_proBadge: 'PRO NUVEM REAL-TIME',
      s_basicBadge: 'BÁSICO SÓ LOCAL',
      s_guestBadge: 'DEMO / VISITANTE',
      s_proTitle: '💎 PLANO PREMIUM PRO ATIVO',
      s_proDesc: 'Sincronização Firebase Real-time Engine ativa com sucesso. Os dados da sua banca inicial, casa de apostas, movimentos de saldo e boletins estão seguros, integrados e partilhados em tempo real entre o iPhone, Android e este painel Web.',
      s_basicTitle: '⭐ PLANO PREMIUM BÁSICO ATIVO',
      s_basicDesc: 'Acesso premium completo local ativado! Os dados estão salvaguardados apenas localmente neste navegador. Nota de privacidade: se mudar de aparelho ou limpar a cache, as estatísticas e boletins não serão preservados na nuvem.',
      s_guestTitle: '🛠️ ASSINATURA IRUNBETS GUEST / GRATUITO',
      s_guestDesc: 'Está a criar o seu portfólio no modo de demonstração. Para usufruir de segurança permanente desfrutando da nossa rede unificada iOS & Web, escolha o plano ideal:',
      s_benef_1: '✓ Múltiplos Boletins',
      s_benef_2: '✓ Estatísticas Avançadas',
      s_benef_3: '✓ Gestão de Banca Inteligente',
      s_benef_4: '✓ Dicas & Alertas Rápidos',
      s_version: 'Modelo de Subscrições iRunBets v2.5 • iOS & Web Unificados',
      m_regulamento: 'Regulamentos de Boletim (Web)',
      m_observaçoes: 'Observações / Anotação do Evento (Opcional)',
      m_adicionarEv: '+ Adicionar Evento',
    },
    en: {
      badge: 'Active Executive Panel',
      title: 'iRunBets VIP Dashboard',
      desc: 'Probability analysis and integrated registry for absolute bankroll control.',
      tabBanca: '📊 Register & Bankroll',
      tabIa: '✨ IA iRunBets',
      tabFavoritos: '⭐ Teams & Leagues',
      sportFilterTitle: 'Active Sport Filter (1 Click)',
      sportFilterDesc: 'Instantly recalculate ROI, Profits and match history',
      allSports: '🌍 All Sports',
      football: '⚽ Football',
      tennis: '🎾 Tennis',
      basketball: '🏀 Basketball',
      others: '🎲 Others',
      matrixBtn: '📊 LEAGUE / MARKET DETAIL MATRIX',
      bancaInicial: 'Starting Bankroll',
      casaPendente: 'BOOKIE',
      semCasa: '⚠️ NO BOOKMAKER',
      editar: 'Edit',
      bancaDeControlo: 'Risk control bankroll',
      bancaGeralFinal: 'Overall Bankroll',
      globalApostas: 'Total of all bets',
      lucroFiltro: 'Profit in Filter',
      positivo: '▲ POSITIVE',
      variancia: '▼ VARIANCE',
      roiFiltro: 'Filter ROI',
      retornoDesporto: 'Return of the selected sport',
      taxaAcerto: 'Win Rate',
      resolvidas: 'resolved',
      gaugeTitle: 'Quick Read of Reds / Greens / Devolution',
      gaugeDesc: 'Current count and proportion of bets in:',
      gaugeNoBets: 'No bets registered in this sport to render the Neon Gauge.',
      ganhas: 'Won',
      perdidas: 'Lost',
      devolvidas: 'Refunded',
      pendentes: 'Pending',
      simples: 'Singles',
      multiplas: 'Multiples',
      comparadorTitle: '🎯 Singles vs Multiples Comparator',
      comparadorDesc: 'Effectiveness rate of integrated Greens/Reds (iPhone iOS & Web)',
      comparadorNoSlips: 'No synchronized slip (iPhone or Web) to process metrics.',
      boletinsSimples: 'Simple Slips',
      boletinsMultiplos: 'Multiple Slips',
      apostasIphone: 'iPhone Bets:',
      apostasWeb: 'Web Bets:',
      total: 'Total',
      eficacia: 'Efficiency (Greens):',
      registarEntradaBadge: 'Register Real Entry',
      multiplaPopup: 'Multiple Pop-up ↗',
      nomeEvento: 'Event Name / Teams',
      desporto: 'Sport',
      mercadoLinha: 'Market / Line',
      competiçao: 'League / Competition',
      tipoMercado: 'Market Type',
      oddOferecida: 'Offered Odd',
      montante: 'Amount (€)',
      estadoInicial: 'Initial Entry Status',
      registarBtn: 'Register Value Entry 🚀',
      graficoBanca: 'Bankroll Evolution Chart (Real History)',
      bancaAtual: 'Current Bankroll:',
      graficoNoBets: 'Register your bets or select another sport filter to see the evolution.',
      historicoTitle: 'Sports Betting History ({0} in filter)',
      historicoTip: 'Tip: Click on status to toggle outcomes quickly',
      historicoNoBets: 'No bets registered for this sport. Use the left form to add or register!',
      tabelaJogo: 'Game / Sport',
      tabelaMercado: 'Market',
      tabelaOdd: 'Odd',
      tabelaStake: 'Stake',
      tabelaLucro: 'Profit/Loss',
      tabelaData: 'Date',
      tabelaEstado: 'Status',
      tabelaAçao: 'Action',
      painelUnificadoTitle: 'Unified Panel: Bet Slips (iOS & Web)',
      painelUnificadoDesc: 'Segmented and secure real-time space. Your iPhone records (betSlips) and website records (webBetSlips) aggregate here without overlap risk.',
      registarBoletimBtn: 'Register Web Slip 🖥️',
      cloudSys: 'Protected Cloud Sync',
      iphoneLabel: '📱 iPhone',
      webLabel: '🖥️ Web',
      loginPrompt: 'Log in to the iRunBets dashboard to connect and view your real-time slips from the iPhone.',
      loadingMatches: 'Searching for matches on server...',
      noSlipsCloud: 'No active bet slips found in Firebase for this account. Place bets on our native iOS app and they will appear here instantly!',
      boletimSimples: 'Simple Slip',
      boletimMultiplo: 'Multiple Slip',
      apagarPerm: 'Delete permanently?',
      sim: 'Yes 🚨',
      nao: 'No',
      editarBtn: 'Edit 📝',
      apagarBtn: 'Delete 🗑️',
      eventos: 'Events',
      recolher: 'Collapse ▲',
      expandir: 'Expand ▼',
      pE_titulo: 'Results Matrix - Adjusted Mathematical Probability',
      pE_noResult: 'Configure the human factors on the left and click the button to compute Poisson probabilities and combined human factors.',
      pE_mercado1x2: '1X2 Market Probabilities (%)',
      pE_btts: 'Both Teams to Score (BTTS)',
      pE_mais15: 'Over 1.5 Goals',
      pE_mais25: 'Over 2.5 Goals',
      pE_empate: 'Draw (X)',
      pE_vitoria: 'Victory',
      pE_casa: 'Home',
      pE_fora: 'Away',
      pE_gerarBtn: 'Generate Hybrid AI Analysis 🤖📊',
      pE_gerandoText: 'AI Calculating Hybrid Probabilities...',
      pE_relatorioTitle: 'iRunBets Specialist Elite Analytical Report',
      pE_relatorioGerando: 'iR-Engine-v3.5 crossing Poisson matrix with human pitch factors...',
      pE_relatorioSecs: 'This may take a few seconds, processing statistical knowledge collection...',
      pE_relatorioPrompt: 'Ready to write specialist report. Click "Generate Hybrid AI Analysis 🤖📊" to query the advanced model.',
      pE_casaLabel: 'Home Team (Standard expected goals)',
      pE_foraLabel: 'Away Team (Standard expected goals)',
      pE_relvado: 'Pitch conditions',
      pE_lesões: 'Important Injuries (Last minute)',
      pE_condições: 'Weather Conditions',
      pE_motivaçao: 'Motivation',
      t_badge: '⚡ PREMIUM STATISTICA CONSOLE (14" COCKPIT MONITOR)',
      t_sub: 'IrUnBets Advanced Analytical Core • Market Segment:',
      t_fechar: '✕ CLOSE TERMINAL',
      t_diagnostico: 'Intelligent Segment Diagnosis',
      t_diagnosticoDesc: 'The statistical data presented results from all bets placed based on the selected sport. The simulator recalculated all metrics at runtime to power this dashboard.',
      t_resumo: 'Status Summary',
      t_leaguesTitle: 'Active Leagues & Competitions (Efficiency 🏆)',
      t_leaguesSub: 'Real hit rate and accumulated net return by sports league',
      t_marketsTitle: 'Markets Behavior (Focus 🎯)',
      t_marketsSub: 'Investment ROI proportional to each type of market',
      t_vol: 'Total Stake Volume',
      t_med: 'Average per entry:',
      t_closeBtn: 'Close Console',
      s_estatuto: 'User Subscription Status (Sync iTunes & Web)',
      s_proBadge: 'PRO CLOUD REAL-TIME',
      s_basicBadge: 'BASIC LOCAL ONLY',
      s_guestBadge: 'DEMO / GUEST',
      s_proTitle: '💎 ACTIVE PREMIUM PRO PLAN',
      s_proDesc: 'Firebase Real-time Engine synchronization active successfully. Your initial bankroll, bookmaker, balance movements and bet slips info are secure, integrated and shared in real-time between iPhone, Android and this Web panel.',
      s_basicTitle: '⭐ ACTIVE PREMIUM BASIC PLAN',
      s_basicDesc: 'Full local premium access activated! Data is saved only locally in this browser. Privacy note: if you change devices or clear cache, statistics and slips will not be preserved in the cloud.',
      s_guestTitle: '🛠️ IRUNBETS GUEST / FREE SUBSCRIPTION',
      s_guestDesc: 'You are using the classic demonstration mode. To enjoy permanent storage security and native real-time sync, select a plan below (mirrored with App Store):',
      s_benef_1: '✓ Multiple Slips',
      s_benef_2: '✓ Advanced Statistics',
      s_benef_3: '✓ Smart Bankroll Management',
      s_benef_4: '✓ Quick Tips & Alerts',
      s_version: 'iRunBets Subscription Model v2.5 • iOS & Web Unified',
      m_regulamento: 'Slip Regulations (Web)',
      m_observaçoes: 'Observations / Event Note (Optional)',
      m_adicionarEv: '+ Add Event',
    },
    fr: {
      badge: 'Panneau exécutif actif',
      title: 'Tableau de bord VIP iRunBets',
      desc: 'Analyse probabiliste et registre intégré pour un contrôle absolu de la bankroll.',
      tabBanca: '📊 Registre & Bankroll',
      tabIa: '✨ IA iRunBets',
      tabFavoritos: '⭐ Équipes & Ligues',
      sportFilterTitle: 'Filtre de sport actif (1 Clic)',
      sportFilterDesc: 'Recalculez instantanément le ROI, les gains et l\'historique des matchs',
      allSports: '🌍 Tous les Sports',
      football: '⚽ Football',
      tennis: '🎾 Tennis',
      basketball: '🏀 Basket-ball',
      others: '🎲 Autres',
      matrixBtn: '📊 MATRICE DES DETAILS LIGUES / MARCHES',
      bancaInicial: 'Bankroll Initiale',
      casaPendente: 'CASA',
      semCasa: '⚠️ SANS BOOKMAKER',
      editar: 'Modifier',
      bancaDeControlo: 'Bankroll de contrôle des risques',
      bancaGeralFinal: 'Bankroll Globale Finale',
      globalApostas: 'Total de tous les paris',
      lucroFiltro: 'Bénéfice du Filtre',
      positivo: '▲ POSITIF',
      variancia: '▼ VARIANCE',
      roiFiltro: 'ROI du Filtre',
      retornoDesporto: 'Retour du sport sélectionné',
      taxaAcerto: 'Taux de Réussite',
      resolvidas: 'résolus',
      gaugeTitle: 'Lecture rapide des Reds / Greens / Devolution',
      gaugeDesc: 'Compte courant et proportion des paris en:',
      gaugeNoBets: 'Aucun pari enregistré dans ce sport pour afficher le Neon Gauge.',
      ganhas: 'Gagnés',
      perdidas: 'Perdus',
      devolvidas: 'Remboursés',
      pendentes: 'En attente',
      simples: 'Simples',
      multiplas: 'Multiples',
      comparadorTitle: '🎯 Comparateur Simples vs Multiples',
      comparadorDesc: 'Taux d\'efficacité des Greens/Reds intégrés (iPhone iOS & Web)',
      comparadorNoSlips: 'Aucun bulletin synchronisé (iPhone ou Web) pour traiter les statistiques.',
      boletinsSimples: 'Bulletins Simples',
      boletinsMultiplos: 'Bulletins Multiples',
      apostasIphone: 'Paris iPhone:',
      apostasWeb: 'Paris Web:',
      total: 'Total',
      eficacia: 'Efficacité (Greens):',
      registarEntradaBadge: 'Enregistrer Entrée Réelle',
      multiplaPopup: 'Multiple Pop-up ↗',
      nomeEvento: 'Nom de l\'événement / Équipes',
      desporto: 'Sport',
      mercadoLinha: 'Marché / Ligne',
      competiçao: 'Ligue / Compétition',
      tipoMercado: 'Type de Marché',
      oddOferecida: 'Cote Offerte',
      montante: 'Montant (€)',
      estadoInicial: 'Statut d\'entrée initial',
      registarBtn: 'Enregistrer l\'entrée de valeur 🚀',
      graficoBanca: 'Graphique d\'évolution de la Bankroll (Historique réel)',
      bancaAtual: 'Bankroll Actuelle:',
      graficoNoBets: 'Enregistrez vos paris ou sélectionnez un autre filtre pour voir l\'évolution.',
      historicoTitle: 'Historique des paris sportifs ({0} dans le filtre)',
      historicoTip: 'Astuce : Cliquez sur le statut pour changer d\'issue rapidement',
      historicoNoBets: 'Aucun pari enregistré pour ce sport. Utilisez le formulaire de gauche pour en ajouter !',
      tabelaJogo: 'Match / Sport',
      tabelaMercado: 'Marché',
      tabelaOdd: 'Cote',
      tabelaStake: 'Mise',
      tabelaLucro: 'Bénéfice/Perte',
      tabelaData: 'Date',
      tabelaEstado: 'Statut',
      tabelaAçao: 'Action',
      painelUnificadoTitle: 'Panneau Unifié : Bulletins de Paris (iOS & Web)',
      painelUnificadoDesc: 'Espace segmenté et sécurisé en temps réel. Vos enregistrements iPhone (betSlips) et site (webBetSlips) s\'agrègent ici sans risque de chevauchement.',
      registarBoletimBtn: 'Enregistrer bulletin Web 🖥️',
      cloudSys: 'Synchronisation Cloud Protégée',
      iphoneLabel: '📱 iPhone',
      webLabel: '🖥️ Web',
      loginPrompt: 'Connectez-vous au panneau iRunBets pour lier et afficher vos bulletins en temps réel depuis l\'iPhone.',
      loadingMatches: 'Recherche de correspondances sur le serveur...',
      noSlipsCloud: 'Aucun bulletin de pari actif trouvé dans Firebase pour ce compte. Placez des paris sur notre application native iOS !',
      boletimSimples: 'Bulletin Simple',
      boletimMultiplo: 'Bulletin Multiple',
      apagarPerm: 'Supprimer définitivement ?',
      sim: 'Oui 🚨',
      nao: 'Non',
      editarBtn: 'Modifier 📝',
      apagarBtn: 'Supprimer 🗑️',
      eventos: 'Événements',
      recolher: 'Plier ▲',
      expandir: 'Déplier ▼',
      pE_titulo: 'Matrice des Résultats - Probabilité Mathématique Ajustée',
      pE_noResult: 'Définissez les facteurs humains à gauche et cliquez sur le bouton pour calculer les probabilités de Poisson et les facteurs humains combinés.',
      pE_mercado1x2: 'Probabilités du Marché 1X2 (%)',
      pE_btts: 'Les deux équipes marquent (BTTS)',
      pE_mais15: 'Plus de 1.5 buts',
      pE_mais25: 'Plus de 2.5 buts',
      pE_empate: 'Nul (X)',
      pE_vitoria: 'Victoire',
      pE_casa: 'Domicile',
      pE_fora: 'Extérieur',
      pE_gerarBtn: 'Générer l\'analyse IA Hybride 🤖📊',
      pE_gerandoText: 'IA En cours de calcul des probabilités...',
      pE_relatorioTitle: 'Rapport Analytique d\'Élite iRunBets Specialist',
      pE_relatorioGerando: 'iR-Engine-v3.5 croisant la matrice de Poisson avec les facteurs humains du terrain...',
      pE_relatorioSecs: 'Cela peut prendre quelques secondes, traitement de la collecte des connaissances statistiques...',
      pE_relatorioPrompt: 'Prêt à générer le rapport expert. Cliquez sur "Générer l\'analyse IA Hybride 🤖📊" pour consulter le modèle avancé.',
      pE_casaLabel: 'Équipe Domicile (Buts attendus standards)',
      pE_foraLabel: 'Équipe Extérieur (Buts attendus standards)',
      pE_relvado: 'État du terrain',
      pE_lesões: 'Blessures importantes (Dernière minute)',
      pE_condições: 'Conditions Climatiques',
      pE_motivaçao: 'Motivation',
      t_badge: '⚡ CONSOLE PREMIUM DE STATISTIQUES (MONITEUR COCKPIT 14")',
      t_sub: 'IrUnBets Advanced Analytical Core • Segment de Marché:',
      t_fechar: '✕ FERMER LA CONSOLE',
      t_diagnostico: 'Diagnostic Intelligent du Segment',
      t_diagnosticoDesc: 'Les données statistiques présentées résultent de tous les paris placés sur le sport sélectionné. Le simulateur a recalculé toutes les métriques à l\'exécution.',
      t_resumo: 'Résumé du statut',
      t_leaguesTitle: 'Compétitions & Ligues Actives (Efficacité 🏆)',
      t_leaguesSub: 'Taux de réussite réel et rendement net cumulé par ligue',
      t_marketsTitle: 'Comportement des Marchés (Focus 🎯)',
      t_marketsSub: 'ROI d\'investissement proportionnel à chaque type de marché',
      t_vol: 'Volume Total des Mises',
      t_med: 'Moyenne par entrée:',
      t_closeBtn: 'Fermer la Console',
      s_estatuto: 'Statut de l\'abonnement de l\'utilisateur (Sync iTunes & Web)',
      s_proBadge: 'PRO CLOUD EN TEMPS REEL',
      s_basicBadge: 'BASIQUE LOCAL SEULEMENT',
      s_guestBadge: 'DEMO / INVITÉ',
      s_proTitle: '💎 PLAN PREMIUM PRO ACTIF',
      s_proDesc: 'Synchronisation Firebase Real-time Engine active avec succès. Votre bankroll, bookmaker, mouvements de solde et bulletins de paris sont sécurisés et partagés en temps réel.',
      s_basicTitle: '⭐ PLAN PREMIUM BASIQUE ACTIF',
      s_basicDesc: 'Accès premium local complet activé ! Les données sont sauvegardées uniquement dans ce navigateur.',
      s_guestTitle: '🛠️ ABONNEMENT IRUNBETS GUEST / GRATUIT',
      s_guestDesc: 'Vous utilisez le mode de démonstration. Pour bénéficier de la sécurité de stockage permanent, sélectionnez un forfait ci-dessous :',
      s_benef_1: '✓ Bulletins Multiples',
      s_benef_2: '✓ Statistiques Avancées',
      s_benef_3: '✓ Gestion de la Bankroll',
      s_benef_4: '✓ Conseils & Alertes',
      s_version: 'Modèle d\'abonnements iRunBets v2.5 • iOS & Web Unifiés',
      m_regulamento: 'Règlement des bulletins (Web)',
      m_observaçoes: 'Observations / Note d\'événement (Optionnel)',
      m_adicionarEv: '+ Ajouter Événement',
    },
    it: {
      badge: 'Pannello esecutivo attivo',
      title: 'Dashboard VIP iRunBets',
      desc: 'Analisi probabilistica e registro integrato per il controllo assoluto del bankroll.',
      tabBanca: '📊 Registro & Bankroll',
      tabIa: '✨ IA iRunBets',
      tabFavoritos: '⭐ Squadre & Leghe',
      sportFilterTitle: 'Filtro Sport Attivo (1 Clic)',
      sportFilterDesc: 'Ricalcola istantaneamente ROI, profitti e cronologia dei match',
      allSports: '🌍 Tutti gli Sport',
      football: '⚽ Calcio',
      tennis: '🎾 Tennis',
      basketball: '🏀 Pallacanestro',
      others: '🎲 Altri',
      matrixBtn: '📊 MATRICE DETTAGLI LEGHE / MERCATI',
      bancaInicial: 'Bankroll Iniziale',
      casaPendente: 'BOOKIE',
      semCasa: '⚠️ SENZA BOOKMAKER',
      editar: 'Modifica',
      bancaDeControlo: 'Bankroll per il controllo del rischio',
      bancaGeralFinal: 'Bankroll Finale Generale',
      globalApostas: 'Totale di tutte le scommesse',
      lucroFiltro: 'Profitto nel Filtro',
      positivo: '▲ POSITIVO',
      variancia: '▼ VARIANZA',
      roiFiltro: 'ROI del Filtro',
      retornoDesporto: 'Rendimento dello sport selezionato',
      taxaAcerto: 'Percentuale di Successo',
      resolvidas: 'risolte',
      gaugeTitle: 'Lettura Rapida di Reds / Greens / Devolution',
      gaugeDesc: 'Conteggio corrente e proporzione delle scommesse in:',
      gaugeNoBets: 'Nessuna scommessa registrata in questo sport per mostrare il Neon Gauge.',
      ganhas: 'Vinte',
      perdidas: 'Perse',
      devolvidas: 'Rimborsate',
      pendentes: 'In attesa',
      simples: 'Singole',
      multiplas: 'Multiple',
      comparadorTitle: '🎯 Comparatore Singole vs Multiple',
      comparadorDesc: 'Tasso di efficacia dei Greens/Reds integrati (iPhone iOS & Web)',
      comparadorNoSlips: 'Nessuna schedina sincronizzata (iPhone o Web) per elaborare le metriche.',
      boletinsSimples: 'Schedine Singole',
      boletinsMultiplos: 'Schedine Multiple',
      apostasIphone: 'Scommesse iPhone:',
      apostasWeb: 'Scommesse Web:',
      total: 'Totale',
      eficacia: 'Efficacia (Greens):',
      registarEntradaBadge: 'Registra Scommessa Reale',
      multiplaPopup: 'Multipla Pop-up ↗',
      nomeEvento: 'Nome Evento / Squadre',
      desporto: 'Sport',
      mercadoLinha: 'Mercato / Linea',
      competiçao: 'Lega / Competizione',
      tipoMercado: 'Tipo di Mercato',
      oddOferecida: 'Quota Offerta',
      montante: 'Importo (€)',
      estadoInicial: 'Stato Iniziale Scommessa',
      registarBtn: 'Registra Scommessa di Valore 🚀',
      graficoBanca: 'Grafico Evoluzione Bankroll (Cronologia Reale)',
      bancaAtual: 'Bankroll Attuale:',
      graficoNoBets: 'Registra le scommesse o seleziona un altro filtro per vedere l\'evoluzione.',
      historicoTitle: 'Cronologia scommesse sportive ({0} nel filtro)',
      historicoTip: 'Suggerimento: clicca sullo stato per cambiare rapidamente l\'esito',
      historicoNoBets: 'Nessuna scommessa registrata per questo sport. Usa il modulo a sinistra per aggiungerne una!',
      tabelaJogo: 'Partita / Sport',
      tabelaMercado: 'Mercato',
      tabelaOdd: 'Quota',
      tabelaStake: 'Puntata',
      tabelaLucro: 'Profitto/Perdita',
      tabelaData: 'Data',
      tabelaEstado: 'Stato',
      tabelaAçao: 'Azione',
      painelUnificadoTitle: 'Pannello Unificato: Schedine di Scommessa (iOS & Web)',
      painelUnificadoDesc: 'Spazio segmentato e sicuro in tempo reale. I record del tuo iPhone (betSlips) e del sito (webBetSlips) si aggregano qui senza rischio di sovrapposizioni.',
      registarBoletimBtn: 'Registra Schedina Web 🖥️',
      cloudSys: 'Sincronizzazione Cloud Protetta',
      iphoneLabel: '📱 iPhone',
      webLabel: '🖥️ Web',
      loginPrompt: 'Accedi al pannello iRunBets per collegare e visualizzare le schedine in tempo reale dall\'iPhone.',
      loadingMatches: 'Ricerca match sul server...',
      noSlipsCloud: 'Nessuna schedina attiva trovata in Firebase per questo account. Scommetti sulla nostra app nativa iOS !',
      boletimSimples: 'Schedina Semplice',
      boletimMultiplo: 'Schedina Multipla',
      apagarPerm: 'Eliminare permanentemente?',
      sim: 'Sì 🚨',
      nao: 'No',
      editarBtn: 'Modifica 📝',
      apagarBtn: 'Elimina 🗑️',
      eventos: 'Eventi',
      recolher: 'Riduci ▲',
      expandir: 'Espandi ▼',
      pE_titulo: 'Matrice Risultati - Probabilità Matematica Regolata',
      pE_noResult: 'Definisci i fattori umani a sinistra e clicca sul pannello per calcolare le probabilità di Poisson e i fattori umani combinati.',
      pE_mercado1x2: 'Probabilità del Mercato 1X2 (%)',
      pE_btts: 'Entrambe le Squadre Segnano (BTTS)',
      pE_mais15: 'Più di 1.5 Gol',
      pE_mais25: 'Più di 2.5 Gol',
      pE_empate: 'Pareggio (X)',
      pE_vitoria: 'Vittoria',
      pE_casa: 'Casa',
      pE_fora: 'Fuori',
      pE_gerarBtn: 'Genera Analisi IA Ibrida 🤖📊',
      pE_gerandoText: 'IA Calcolo delle probabilità ibride...',
      pE_relatorioTitle: 'Rapporto Analitico d\'Élite Specialist iRunBets',
      pE_relatorioGerando: 'iR-Engine-v3.5 incrocio tra Poisson e fattori umani del campo...',
      pE_relatorioSecs: 'Questo potrebbe richiedere alcuni secondi, elaborazione dati statistici...',
      pE_relatorioPrompt: 'Pronto per redigere il rapporto esperto. Clicca su "Genera Analisi IA Ibrida 🤖📊" per consultare il modello avanzato.',
      pE_casaLabel: 'Squadra di casa (Gol attesi standard)',
      pE_foraLabel: 'Squadra ospite (Gol attesi standard)',
      pE_relvado: 'Stato del campo',
      pE_lesões: 'Infortuni importanti (Ultimo minuto)',
      pE_condições: 'Condizioni Climatiche',
      pE_motivaçao: 'Motivazione',
      t_badge: '⚡ PREMIUM CONSOLE STATISTICHE (MONITOR COCKPIT 14")',
      t_sub: 'IrUnBets Advanced Analytical Core • Segmento di Mercato:',
      t_fechar: '✕ CHIUDI CONSOLE',
      t_diagnostico: 'Diagnostica Segmento Intelligente',
      t_diagnosticoDesc: 'I dati statistici presentati derivano da tutte le scommesse piazzate sullo sport selezionato. Il simulatore ha ricalcolato le metriche in tempo di esecuzione.',
      t_resumo: 'Riepilogo Stato',
      t_leaguesTitle: 'Competizioni & Leghe Attive (Efficienza 🏆)',
      t_leaguesSub: 'Tasso di vincita reale e rendimento netto accumulato per lega',
      t_marketsTitle: 'Comportamento dei Mercati (Focus 🎯)',
      t_marketsSub: 'ROI di investimento in proporzione a ciascun tipo di mercato',
      t_vol: 'Volume di Puntata Totale',
      t_med: 'Media per scommessa:',
      t_closeBtn: 'Chiudi Console',
      s_estatuto: 'Stato dell\'abbonamento utente (Sync iTunes & Web)',
      s_proBadge: 'PRO CLOUD IN TEMPO REALE',
      s_basicBadge: 'BASIC SOLO LOCALE',
      s_guestBadge: 'DEMO / OSPITE',
      s_proTitle: '💎 PIANO PREMIUM PRO ATTIVO',
      s_proDesc: 'Sincronizzazione Firebase Real-time Engine attiva con successo. I dati del tuo bankroll, bookmaker, movimenti e schedine sono al sicuro e sincronizzati.',
      s_basicTitle: '⭐ PIANO PREMIUM BASIC ATTIVO',
      s_basicDesc: 'Accesso premium locale completo attivato! I dati sono salvati solo localmente su questo browser.',
      s_guestTitle: '🛠️ ABONNEMENT IRUNBETS GUEST / GRATUITO',
      s_guestDesc: 'Stai utilizzando la modalità dimostrazione. Per usufruire della sicurezza dei dati permanente, seleziona un piano qui sotto:',
      s_benef_1: '✓ Schedine Multiple',
      s_benef_2: '✓ Statistiche Avanzate',
      s_benef_3: '✓ Bankroll Management Intelligente',
      s_benef_4: '✓ Consigli & Allarmi Rapidi',
      s_version: 'Modello di abbonamento iRunBets v2.5 • iOS & Web Unificato',
      m_regulamento: 'Regolamenti Schedine (Web)',
      m_observaçoes: 'Osservazioni / Note dell\'evento (Opzionale)',
      m_adicionarEv: '+ Aggiungi Evento',
    },
    de: {
      badge: 'Aktives Führungs-Panel',
      title: 'iRunBets VIP-Dashboard',
      desc: 'Wahrscheinlichkeitsanalyse und integriertes Register für die absolute Bankroll-Kontrolle.',
      tabBanca: '📊 Register & Bankroll',
      tabIa: '✨ KI iRunBets',
      tabFavoritos: '⭐ Teams & Ligen',
      sportFilterTitle: 'Aktiver Sportfilter (1 Klick)',
      sportFilterDesc: 'Recalculieren Sie ROI, Gewinne und Match-Historie sofort neu.',
      allSports: '🌍 Alle Sportarten',
      football: '⚽ Fußball',
      tennis: '🎾 Tennis',
      basketball: '🏀 Basketball',
      others: '🎲 Andere',
      matrixBtn: '📊 LIGA- / MARKT-DETAIL-MATRIX',
      bancaInicial: 'Startguthaben',
      casaPendente: 'CASA',
      semCasa: '⚠️ KEIN BUCHMACHER',
      editar: 'Bearbeiten',
      bancaDeControlo: 'Risikokontrolle Bankroll',
      bancaGeralFinal: 'Gesamte Endbankroll',
      globalApostas: 'Gesamtsumme aller Wetten',
      lucroFiltro: 'Gewinn im Filter',
      positivo: '▲ POSITIV',
      variancia: '▼ VARIANZ',
      roiFiltro: 'Filter-ROI',
      retornoDesporto: 'Rendite der ausgewählten Sportart',
      taxaAcerto: 'Erfolgsquote',
      resolvidas: 'aufgelöst',
      gaugeTitle: 'Schnellansicht von Reds / Greens / Devolution',
      gaugeDesc: 'Aktuelle Wetten-Anzahl und Proportion in:',
      gaugeNoBets: 'Es wurden keine Wetten für diese Sportart registriert, um den Neon Gauge anzuzeigen.',
      ganhas: 'Gewonnen',
      perdidas: 'Verloren',
      devolvidas: 'Erstattet',
      pendentes: 'Ausstehend',
      simples: 'Einzelwetten',
      multiplas: 'Kombiwetten',
      comparadorTitle: '🎯 Einzel- vs. Kombiwettenvergleich',
      comparadorDesc: 'Erfolgsquote integrierter Greens/Reds (iPhone iOS & Web)',
      comparadorNoSlips: 'Kein synchronisierter Wettschein (iPhone oder Web) zur Datenverarbeitung vorhanden.',
      boletinsSimples: 'Einzelscheine',
      boletinsMultiplos: 'Kombischeine',
      apostasIphone: 'iPhone-Wetten:',
      apostasWeb: 'Web-Wetten:',
      total: 'Gesamt',
      eficacia: 'Effizienz (Greens):',
      registarEntradaBadge: 'Echten Wetteintrag erfassen',
      multiplaPopup: 'Kombi-Popup ↗',
      nomeEvento: 'Event-Name / Teams',
      desporto: 'Sportart',
      mercadoLinha: 'Markt / Linie',
      competiçao: 'Liga / Wettbewerb',
      tipoMercado: 'Markttyp',
      oddOferecida: 'Angebotene Quote',
      montante: 'Einsatz (€)',
      estadoInicial: 'Anfänglicher Wettstatus',
      registarBtn: 'Wetteintrag buchen 🚀',
      graficoBanca: 'Bankroll-Entwicklungschart (Reale Historie)',
      bancaAtual: 'Aktuelles Guthaben:',
      graficoNoBets: 'Registrieren Sie Ihre Wetten, um die Entwicklung zu sehen.',
      historicoTitle: 'Sportwetten-Historie ({0} im Filter)',
      historicoTip: 'Tipp: Klicken Sie auf den Status, um das Ergebnis schnell umzuschalten',
      historicoNoBets: 'Keine Wetten für diesen Sport registriert. Verwenden Sie das linke Formular zum Hinzufügen!',
      tabelaJogo: 'Spiel / Sportart',
      tabelaMercado: 'Markt',
      tabelaOdd: 'Quote',
      tabelaStake: 'Einsatz',
      tabelaLucro: 'Gewinn/Verlust',
      tabelaData: 'Datum',
      tabelaEstado: 'Status',
      tabelaAçao: 'Aktion',
      painelUnificadoTitle: 'Vereinheitlichtes Panel: Wettscheine (iOS & Web)',
      painelUnificadoDesc: 'Segmentierter und sicherer Echtzeitbereich. Ihre iPhone-Einträge (betSlips) und Web-Einträge (webBetSlips) werden ohne Risiko von Überschneidungen zusammengeführt.',
      registarBoletimBtn: 'Web-Wettschein registrieren 🖥️',
      cloudSys: 'Geschützte Cloud-Sychronisierung',
      iphoneLabel: '📱 iPhone',
      webLabel: '🖥️ Web',
      loginPrompt: 'Melden Sie sich im iRunBets-Panel an, um Ihre Wettscheine vom iPhone in Echtzeit anzuzeigen.',
      loadingMatches: 'Suche nach Spielen auf dem Server...',
      noSlipsCloud: 'Keine aktiven Wettscheine in Firebase für dieses Konto gefunden. Platzieren Sie Wetten auf unserer nativen iOS-App!',
      boletimSimples: 'Einzelschein',
      boletimMultiplo: 'Kombischein',
      apagarPerm: 'Dauerhaft löschen?',
      sim: 'Ja 🚨',
      nao: 'Nein',
      editarBtn: 'Bearbeiten 📝',
      apagarBtn: 'Löschen 🗑️',
      eventos: 'Ereignisse',
      recolher: 'Einklappen ▲',
      expandir: 'Ausklappen ▼',
      pE_titulo: 'Ergebnis-Matrix - Angepasste mathematische Wahrscheinlichkeit',
      pE_noResult: 'Definieren Sie links die menschlichen Faktoren und klicken Sie auf die Schaltfläche, um die Poisson-Wahrscheinlichkeiten und kombinierten Faktoren zu berechnen.',
      pE_mercado1x2: 'Wahrscheinlichkeiten für den 1X2-Markt (%)',
      pE_btts: 'Beide Teams treffen (BTTS)',
      pE_mais15: 'Über 1.5 Tore',
      pE_mais25: 'Über 2.5 Tore',
      pE_empate: 'Unentschieden (X)',
      pE_vitoria: 'Sieg',
      pE_casa: 'Heim',
      pE_fora: 'Auswärts',
      pE_gerarBtn: 'Hybride KI-Analyse generieren 🤖📊',
      pE_gerandoText: 'KI berechnet hybride Wahrscheinlichkeiten...',
      pE_relatorioTitle: 'iRunBets Specialist Elite analytischer Bericht',
      pE_relatorioGerando: 'iR-Engine-v3.5 kreuzt Poisson-Matrix mit menschlichen Spielfeldfaktoren...',
      pE_relatorioSecs: 'Dies kann einige Sekunden dauern. Statistische Datensätze werden verarbeitet...',
      pE_relatorioPrompt: 'Bereit für den Expertenbericht. Klicken Sie auf "Hybride KI-Analyse generieren 🤖📊", um das Modell abzufragen.',
      pE_casaLabel: 'Heimmannschaft (Standarderwartete Tore)',
      pE_foraLabel: 'Auswärtsmannschaft (Standarderwartete Tore)',
      pE_relvado: 'Spielfeldzustand',
      pE_lesões: 'Wichtige Verletzungen (Letzte Minute)',
      pE_condições: 'Wettbedingungen',
      pE_motivaçao: 'Motivation',
      t_badge: '⚡ STATISTIKKONSOLE (14" COCKPIT-MONITOR)',
      t_sub: 'IrUnBets Advanced Analytical Core • Marktsegment:',
      t_fechar: '✕ TERMINAL SCHLIESSEN',
      t_diagnostico: 'Intelligente Segmentdiagnose',
      t_diagnosticoDesc: 'Die dargestellten statistischen Daten basieren auf allen Wetten der gewählten Sportart. Der Simulator berechnet alle Kennzahlen in Echtzeit neu.',
      t_resumo: 'Statuszusammenfassung',
      t_leaguesTitle: 'Aktive Ligen & Wettbewerbe (Effizienz 🏆)',
      t_leaguesSub: 'Reale Trefferquote und kumulierte Nettorendite nach Sportliga',
      t_marketsTitle: 'Marktverhalten (Fokus 🎯)',
      t_marketsSub: 'Investitions-ROI proportional zu jeder Wettart',
      t_vol: 'Gesamteinsatzvolumen',
      t_med: 'Durchschnitt pro Eintrag:',
      t_closeBtn: 'Konsole Schließen',
      s_estatuto: 'Benutzer-Abonnementstatus (Sync iTunes & Web)',
      s_proBadge: 'PRO ECHTZEIT-CLOUD',
      s_basicBadge: 'BASIC NUR LOKAL',
      s_guestBadge: 'DEMO / GAST',
      s_proTitle: '💎 AKTIVER PREMIUM PRO PLAN',
      s_proDesc: 'Firebase Real-Time Engine-Synchronisierung erfolgreich aktiv. Ihre Bankroll-, Buchmacher-, Kontobewegungen- und Wettschein-Daten sind sicher und synchronisiert.',
      s_basicTitle: '⭐ AKTIVER PREMIUM BASIC PLAN',
      s_basicDesc: 'Vollständiger lokaler Premium-Zugriff aktiviert! Daten werden nur lokal auf diesem Browser gespeichert.',
      s_guestTitle: '🛠️ IRUNBETS GUEST / MEIN ABONNEMENT',
      s_guestDesc: 'Sie verwenden den klassischen Demonstrationsmodus. Um von dauerhafter Datensicherheit zu profitieren, wählen Sie ein Paket aus:',
      s_benef_1: '✓ Kombischeine',
      s_benef_2: '✓ Erweiterte Statistiken',
      s_benef_3: '✓ Intelligentes Bankroll-Management',
      s_benef_4: '✓ Schnelle Tipps & Alarme',
      s_version: 'iRunBets-Abonnementmodell v2.5 • iOS & Web vereint',
      m_regulamento: 'Regulierung der Wettscheine (Web)',
      m_observaçoes: 'Bemerkungen / Eventnotizen (Optional)',
      m_adicionarEv: '+ Ereignis hinzufügen',
    },
  };

export const getVipLabels = (language: string) => {
  return labelsMap[language] || labelsMap.pt;
};
